version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
    steps:
      - codecov/upload:
          file: target/my-reports

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
